### ISSUE TITLE
Unable to Run Example Project

### ISSUE THREAD

**Issue by calendee** [z0al/react-native-styled.macro#20]
Hello!

I've tried running the example project in the repo as follows:

- Clone the branch
- `cd example`
- `yarn install`
- `expo start`
- Open in simulator.

Unfortunately, I always get this error:

> Unable to resolve module `react-native-styled.macro/lib` from `App.tsx`: react-native-styled.macro/lib could not be found within the project.

![react-native-styled macro-example-error](https://user-images.githubusercontent.com/57374/97871033-7cab1580-1cd9-11eb-91c5-b6ee6e6a997c.png)

I've tried all the suggestions for resolving with no success.

Do you know how I can run the example without getting this error?

**Comment by z0al** [comment]
:wave:  @calendee . Thank you for trying this out.

> Unfortunately, I always get this error

That's probably a mistake on my end. I will try to take a look after work today and come back to you.

**Comment by z0al** [comment]
Updating to `v0.6.3` should fix this issue. Thanks for reporting this.

**Comment by calendee** [comment]
That did the trick 💥! Thanks so much!
