### ISSUE TITLE
styled function inside prop

### ISSUE THREAD

**Issue by branislaav** [z0al/react-native-styled.macro#21]
Is there function that can be used in component prop such as `containerStyles={styledFn(['my-3'])}` ?

**Comment by branislaav** [comment]
I just realized that this can be achvied by `containerStyles={styledFn(['my-3']).style}` is this recommended approach or is there another way ?

**Comment by z0al** [comment]
> I just realized that this can be acheived by containerStyles={styledFn(['my-3']).style} 

That's correct. `styledFn` will always return an object with `{style: [...], ...otherProps}`.

> Is this recommended approach or is there another way ?

That's the only way for now. Would love to know if you have some suggestions.

**Comment by z0al** [comment]
I will close this for now since there is nothing actionable but feel free to ask more questions.
