### ISSUE TITLE
config / plugins

### ISSUE THREAD

**Issue by ajsmth** [z0al/react-native-styled.macro#52]
hi there - this library looks amazing. 

i basically wasted a bunch of time building a runtime version of this, but this looks way better. is there anything i can do to help? i know adding custom configs is likely the next step, also are you thinking of a plugin system? 

cheers!

**Comment by codinronan** [comment]
@ajsmth yeah I am sitting here trying to decide if I use your work, or react-native-styled.macro. 

What your work has going for it is 2 things:
* You can use "style strings" directly, which are much more readable than verbose arrays
* The way it *looks* like this project works, it's not possible to create a utility function that encapsulates hook usage, for example useColorScheme, because the babel plugin is looking for specific uses. That is, you can't do something like this:

```
export default utility = (styles) => {
    const windowVariant = useWindowVariant();
    // const scheme = useColorScheme(); // for example

    return styled(styles, {
        ...windowVariant /* other variants like useColorScheme() */,
    });
};
```

```
const MyComponent = () => {
	return (
		<Text {...utility(['w-full', 'md:w-64'])}>
		    My text
		</Text>
	);
};
```

This means that extended usage of this project will make every declared component pretty verbose - or am I missing something?

**Comment by ajsmth** [comment]
i realize this as well - i'm continuing to work on the api in tailwind-react-native as i dont think its a waste of time to provide runtime extendability. would be nice to have some of the static optimizations though!

**Comment by codinronan** [comment]
The babel plugin approach is still a valid one. There are a couple of examples of this out there - we can sync up over at your repo

**Comment by ajsmth** [comment]
sounds great!

**Comment by z0al** [comment]
Hey :wave: Glad you found this macro useful!

>  is there anything i can do to help? 

Thanks for the offer. I'm struggling to get TypeScript completion to work. I invested a couple of days trying to get it to work utilizing the new v4.1 template literal. While it works locally in VS Code it all goes to trash when I push things to npm, not sure why :)

> i know adding custom configs is likely the next step, also are you thinking of a plugin system?

I have a very rough idea of how a plugin system might look like but I don't want to push things forward before experimenting with the current design more and explore its limits. I'm dogfooding this lib in a private project to do that. Feedback is ofc always appreciated. 

> You can use "style strings" directly, which are much more readable than verbose arrays

Agree. This can be easily added. In fact, that was the first version of this library before announcing it. I will definitely bring it back soon. Also, PR is welcome if you want to do that yourself :)

> Your functions can be extracted into shared utilities. The way it looks like this project works, it's not possible to create a utility function that encapsulates hook usage

True. However, I'm not sure if there is something to be done here. I'm not an expert in compiler stuff but I think this is a fundamental limitation when choosing to generate things at compile time.

> for example useColorScheme, because the babel plugin is looking for specific uses. That is, you can't do something like this:

To workaround that, I personally do this:

```javascript
function useVariants(){
    const windowVariant = useWindowVariant();
    const const scheme = useColorScheme() 
    // ... more stuff
   return {...windowVariant, ...scheme}
}
```

```javascript
function MyComponent(){
   const variants = useVariants()
   return <Text  {...styled(['text-base', 'other styles...'], variants)}></Text>
}
```

Also, I'm interested to know what kind of "variants" do you usually need?

> i'm continuing to work on the api in tailwind-react-native as i dont think its a waste of time

Didn't have the time to take a look at it but it's definitely not a waste of time :) . I don't think there is a single solution that serves all here.

**Comment by z0al** [comment]
I will create a Roadmap (more like a brain dump) issue to share what I have in mind publically soon.

**Comment by z0al** [comment]
I'd be curious to know how I turns out for you in your library @ajsmth . My first attempt was a hacky runtime version of this based on `tailwind-rn` but I couldn't figure out how to strip unused styles (what purge css does in Tailwind CSS) especially after considering adding support for plugin and custom configs and so on.

It might not be a big deal for RN but I also target Web on my personal work (I'm mainly a web dev) so it raised some concerns for me.

**Comment by ajsmth** [comment]
i've yet to figure that out as well, but i'm hoping to come up with something!

**Comment by z0al** [comment]
> I will create a Roadmap (more like a brain dump) issue to share what I have in mind publically soon.

As promised. I wrote a few points in #55

**Comment by ajsmth** [comment]
hey there - wanted to let you know I've added a naive script to purge unused styles from a json file - I know you mentioned wanted a way to do this in an earlier comment, I took a similar approach to what purgecss would do! cheers

https://github.com/ajsmth/tailwind-react-native

**Comment by z0al** [comment]
Thanks for the update @ajsmth . That sounds like a great solution.
