### ISSUE TITLE
Missing h-full style

### ISSUE THREAD

**Issue by branislaav** [z0al/react-native-styled.macro#67]
Hi, I noticed that there are no percentage height styles. I find myself using h-full a lot but there might be cases when others can be useful as well, is there any reason why there are no percentage heights included in the base theme?

**Comment by z0al** [comment]
I switch between Web & React Native a lot I honestly don't remember if `{height: '100%'}` is actually supported xD. If it works then I'd be happy to add it.

**Comment by z0al** [comment]
I just checked. It works. Would you be interested in opening PR for it?
